=== aleph2c/learning_xslt_with_python/jenni/ch13_schemas/TVGuide.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

<xs:element name="TVGuide">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="Channel" type="Channel" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="start" type="xs:date" use="required" />
    <xs:attribute name="end" type="xs:date" use="required" />
  </xs:complexType>
</xs:element>

<xs:complexType name="Channel">
  <xs:sequence>
    <xs:element name="Name" type="xs:token" />
    <xs:element name="Program" type="Program" maxOccurs="unbounded" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="Program">
  <xs:sequence>
    <xs:element name="Start" type="xs:dateTime" />
    <xs:element name="Duration" type="xs:duration" />
    <xs:element name="Series" type="SeriesRef" />
    <xs:element name="Title" type="xs:token" />
    <xs:element name="Description" type="Inline" minOccurs="0"/>
    <xs:element name="CastList" type="CastList" minOccurs="0" />
    <xs:choice minOccurs="0">
      <xs:element name="Writers" type="Writers" />
      <xs:element ref="Writer" />
    </xs:choice>
    <xs:choice minOccurs="0">
      <xs:element name="Directors" type="Directors" />
      <xs:element ref="Director" />
    </xs:choice>
    <xs:choice minOccurs="0">
      <xs:element name="Producers" type="Producers" />
      <xs:element ref="Producer" />
    </xs:choice>
  </xs:sequence>
  <xs:attribute name="rating" type="Rating" />
  <xs:attribute name="flag" type="Flag" />
  <xs:attribute name="type" type="ProgramType" />
</xs:complexType>

<xs:element name="Title" type="xs:string" />  
  
<xs:simpleType name="SeriesRef">
  <xs:union memberTypes="xs:NMTOKEN">
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:enumeration value="" />
      </xs:restriction>
    </xs:simpleType>
  </xs:union>
</xs:simpleType>

<xs:element name="SeriesList">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="Series" type="Series" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:key name="series">
    <xs:selector xpath="Series" />
    <xs:field xpath="@id" />
  </xs:key>
</xs:element>

<xs:complexType name="Series">
  <xs:sequence>
    <xs:element name="Title" type="xs:token" />
    <xs:element name="Description" type="Inline" />
  </xs:sequence>
  <xs:attribute name="id" type="xs:NMTOKEN" use="required" />
  <xs:attribute name="type" type="ProgramType" use="required" />
</xs:complexType>

<xs:complexType name="Inline" mixed="true">
  <xs:sequence>
    <xs:element ref="_Inline" minOccurs="0" maxOccurs="unbounded" />
  </xs:sequence>
</xs:complexType>

<xs:element name="_Inline" type="Inline" abstract="true" />

<xs:element name="Character" substitutionGroup="_Inline" />
<xs:element name="Actor" substitutionGroup="_Inline" />

<xs:element name="Program" substitutionGroup="_Inline" />
<xs:element name="Series" substitutionGroup="_Inline" />
<xs:element name="Channel" substitutionGroup="_Inline" />

<xs:element name="Link" type="Link" substitutionGroup="_Inline" />

<xs:complexType name="Link">
  <xs:complexContent mixed="true">
    <xs:extension base="Inline">
      <xs:attribute name="href" type="xs:anyURI" />
    </xs:extension>    
  </xs:complexContent>
</xs:complexType>

<xs:complexType name="CastList">
  <xs:sequence>
    <xs:element name="CastMember" type="CastMember" maxOccurs="unbounded" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="CastMember">
  <xs:sequence>
    <xs:element name="Character" type="Person" />
    <xs:element name="Actor" type="Person" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="Person">
  <xs:sequence>
    <xs:element name="Name" type="xs:token" />
    <xs:element name="Description" type="Inline" minOccurs="0" />
  </xs:sequence>
</xs:complexType>

<xs:complexType name="PersonList">
  <xs:sequence maxOccurs="unbounded">
    <xs:element ref="_Person" />
  </xs:sequence>
</xs:complexType>

<xs:element name="_Person" type="Person" abstract="true" />

<xs:element name="Writer" substitutionGroup="_Person" />
<xs:element name="Director" substitutionGroup="_Person" />
<xs:element name="Producer" substitutionGroup="_Person" />

<xs:complexType name="Writers">
  <xs:complexContent>
    <xs:restriction base="PersonList">
      <xs:sequence maxOccurs="unbounded">
        <xs:element ref="Writer" />
      </xs:sequence>
    </xs:restriction>    
  </xs:complexContent>
</xs:complexType>

<xs:complexType name="Directors">
  <xs:complexContent>
    <xs:restriction base="PersonList">
      <xs:sequence maxOccurs="unbounded">
        <xs:element ref="Director" />
      </xs:sequence>
    </xs:restriction>    
  </xs:complexContent>
</xs:complexType>

<xs:complexType name="Producers">
  <xs:complexContent>
    <xs:restriction base="PersonList">
      <xs:sequence maxOccurs="unbounded">
        <xs:element ref="Producer" />
      </xs:sequence>
    </xs:restriction>    
  </xs:complexContent>
</xs:complexType>

<xs:simpleType name="Rating">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="1" />
    <xs:maxInclusive value="10" />
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="Flag">
  <xs:restriction base="xs:token">
    <xs:enumeration value="favorite" />
    <xs:enumeration value="interesting" />
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="ProgramType">
  <xs:restriction base="xs:token">
    <xs:enumeration value="documentary" />
    <xs:enumeration value="soap" />
    <xs:enumeration value="film" />
    <xs:enumeration value="entertainment" />
    <xs:enumeration value="drama" />
    <xs:enumeration value="news" />
    <xs:enumeration value="quiz" />
    <xs:enumeration value="sport" />
    <xs:enumeration value="improvement" />
    <xs:enumeration value="cartoon" />
  </xs:restriction>
</xs:simpleType>

</xs:schema>

=== aleph2c/learning_xslt_with_python/jenni/ch13_schemas/series2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<SeriesList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="TVGuide.xsd">
  <Series id="EastEnders" type="soap">
    <Title>EastEnders</Title>
    <Description>Soap set in the East End of London.</Description>
  </Series>
  <Series id="BBCNews" type="news">
    <Title>BBC News</Title>
    <Description>Daily news and sport.</Description>
  </Series>
  <Series id="QuestionOfSport" type="quiz">
    <Title>A Question Of Sport</Title>
    <Description>Sport quiz show.</Description>
  </Series>
  <Series id="Lottery" type="entertainment">
    <Title>The National Lottery</Title>
    <Description>More people waste their money.</Description>
  </Series>
  <Series id="Panorama" type="news">
    <Title>Panorama</Title>
    <Description>Current issues.</Description>
  </Series>
  <Series id="Snooker" type="sport">
    <Title>Snooker</Title>
    <Description>Snooker.</Description>
  </Series>
  <Series id="HomeFront" type="improvement">
    <Title>Home Front</Title>
    <Description>Home improvements show.</Description>
  </Series>
  <Series id="WildAfrica" type="documentary">
    <Title>Wild Africa</Title>
    <Description>Wildlife documentary.</Description>
  </Series>
  <Series id="Taboo" type="documentary">
    <Title>Taboo</Title>
    <Description>Documentary series on censorship.</Description>
  </Series>
  <Series id="Emmerdale" type="soap">
    <Title>Emmerdale</Title>
    <Description>Soap set in the countryside.</Description>
  </Series>
  <Series id="CoronationStreet" type="soap">
    <Title>Coronation Street</Title>
    <Description>Soap set in the north.</Description>
  </Series>
  <Series id="Millionaire" type="quiz">
    <Title>Who Wants to Be a Millionaire?</Title>
    <Description>Quiz show.</Description>
  </Series>
  <Series id="Channel4News" type="news">
    <Title>Channel 4 News</Title>
    <Description>News and weather.</Description>
  </Series>
  <Series id="SlotArt" type="documentary">
    <Title>Slot Art</Title>
    <Description>Short films on art techniques.</Description>
  </Series>
  <Series id="Brookside" type="soap">
    <Title>Brookside</Title>
    <Description>Soap set in Liverpool.</Description>
  </Series>
  <Series id="Swallow" type="drama">
    <Title>Swallow</Title>
    <Description>Drama about prescription drug use.</Description>
  </Series>
  <Series id="AllyMcBeal" type="drama">
    <Title>Ally McBeal</Title>
    <Description>Drama about single female lawyer.</Description>
  </Series>
  <Series id="5News" type="news">
    <Title>5 News</Title>
    <Description>News and sport.</Description>
  </Series>
  <Series id="MovieChartShow" type="entertainment">
    <Title>The Movie Chart Show</Title>
    <Description>Latest movie news.</Description>
  </Series>
  <Series id="Simpsons" type="cartoon">
    <Title>The Simpsons</Title>
    <Description>Insightful observations on American family life.</Description>
  </Series>
  <Series id="StarTrekVoyager" type="drama">
    <Title>Star Trek: Voyager</Title>
    <Description>Sci-fi series set on a space ship stranded far from earth.</Description>
  </Series>
  <Series id="DarkAngel" type="drama">
    <Title>Dark Angel</Title>
    <Description>Genetically-engineered soldiers in near-future Seattle.</Description>
  </Series>
  <Series id="StarTrekNextGeneration" type="drama">
    <Title>Star Trek: The Next Generation</Title>
    <Description>Sci-fi series starring <Actor>Patrick Stewart</Actor>.</Description>
  </Series>
</SeriesList>
